### ISSUE TITLE
Program Crashing when Changing To Automatic Input

### ISSUE THREAD

**Issue by Hanens178** [OmegaPhi115/Draconic-Evolution-Reactor-Controller#16]
![image](https://user-images.githubusercontent.com/77894148/105613722-b82f1a80-5dc4-11eb-833f-7b945578b479.png)
 
When i try to Change the input to Automatic the Program Crashes and the Reactor explodes after a while. 

Edit: When you turn Fail save on it works

Edit 2: I just tought it was fixed but i didnt turn the reactor on so the Problem is as described

**Comment by TheArchitectIO** [comment]
change line 6 to 'local targetFieldStrengthPercent" and it'll start working. theres a pull request to fix this but has not happened

**Comment by Hanens178** [comment]
> change line 6 to 'local targetFieldStrengthPercent" and it'll start working. theres a pull request to fix this but has not happened
Ah ok thank you 

For Everyone who doesn't know how to edit stuff, go into your Computer and type: edit startup  then press enter. Go to line 6 and change it. Then Press CTRL and Save and then run, and now it should work.
